language: python
python:
    - "3.7"

before_install:
    - "sudo apt-get update"
    - "sudo apt-get install gfortran"
    - "sudo pip install --upgrade pip"
    - "sudo pip install rocketcea"

env: FC=gfortran

install:
    - pip install -r requirements.txt
    
script:
    - py.test
